#!/bin/bash

#
# From default arch .bashrc
#
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

#
# Make bash more friendly
#
shopt -s cdspell  # Correct directory names typo in cd commands
shopt -s nocaseglob  # Correct case errors in commands

#
# Gaming, ensure steam use system libraries (not needed anymore?)
#
#export STEAM_RUNTIME=0

#
# Export dotfiles bin directory
#
export PATH="${PATH}:~/dotfiles/bin"
export PATH="${PATH}:~/dotfiles/arch-ppa"  # todo: check for arch

#
# Python Developpement
#
export PYTHONPATH="${PYTHONPATH}:~/dev/python"

#
# Arch-Linux specific
#
if [ -f "/etc/arch-release" ]; then
  alias _install="sudo pacman -Sy"
  alias _uninstall="sudo pacman -R"
  alias _update="sudo pacman -Syu"
  alias _search="sudo pacman -Ss"
  alias _start="sudo systemctl start"
  alias _stop="sudo systemctl stop"
  alias _status="sudo systemctl status"
  alias _restart="sudo systemctl restart"
  alias _reload="sudo systemctl daemon-reload"
  alias _enable="sudo systemctl enable"
  alias _disable="sudo systemctl disable"
  alias _journalof="sudo journalctl -u"
  alias _journal="sudo journalctl -b -f"
  alias _reboot="sudo systemctl reboot -i"
  alias _arch_ppa_add="arch-ppa add"
  alias _arch_ppa_build="arch-ppa build pkg"
fi

#
# Extract script
#
# src: https://gist.github.com/Jaxmetalmax/f0ec6d2f86474d8d319b
extract () {
if [ -f $1 ] ; then
  case $1 in
    *.tar.bz2) tar xjf $1 ;;
    *.tar.gz) tar xzf $1 ;;
    *.bz2) bunzip2 $1 ;;
    *.rar) rar x $1 ;;
    *.gz) gunzip $1 ;;
    *.tar) tar xf $1 ;;
    *.tbz2) tar xjf $1 ;;
    *.tgz) tar xzf $1 ;;
    *.zip) unzip $1 ;;
    *.Z) uncompress $1 ;;
    *) echo "'$1' cannot be extracted via extract()" ;;
  esac
else
  echo "'$1' is not a valid file"
fi
}

#
# Powerline Integration
#
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. /usr/lib/python3.6/site-packages/powerline/bindings/bash/powerline.sh

#
# Tmux configuration
#

# Load tmux by default
#[[ $TERM != "screen" ]] && exec tmux

#
# Job specific
#
if [ -f "/etc/arch-release" ]; then
  # MAYA SPECIFIC
  export MAYA_DISABLE_CIP=1 # Prevent a crash when loading Maya in Arch
  export MAYA_DISABLE_CER=1
  #export MAYA_COLOR_MANAGEMENT_POLICY_FILE='~/maya/mayaColorManagerProfile.xml'

  # REZ
  export PATH="${PATH}:~/opt/rez/bin/rez"
  export REZ_CONFIG_FILE="~/opt/rezconfig.py"

  # OMTK SPECIFIC
  export PYTHONPATH="${PYTHONPATH}:~/dev/python/omtk/python"

  # SSTK SPECIFIC
  export SSTK_DISABLE_RAVEN=True
  export SSTK_DISABLE_LOGSTASH=True
  export SQUEEZE_SSTK_NO_SENTRY=True
fi

